### ISSUE TITLE
Update to OTP 24

### ISSUE THREAD

**Issue by NduatiK** [elixir-desktop/android-example-app#3]
You mentioned in the [README](https://github.com/elixir-desktop/android-example-app#update-built-in-runtime) that the required changes have been added to master. I can't get an Android build working on Windows, would changing the otp source to otp24 be possible?

**Comment by dominicletz** [comment]
@NduatiK thanks for pinging not sure, why but I didn't actually see your initial post here - will check that out, should be possible that I can upgrade this now.

**Comment by dominicletz** [comment]
@NduatiK this project and the ios sample have been updated to the last official OTP25 25.0.4 -- have fun!

**Comment by NduatiK** [comment]
💚 Thanks
